name = "cf-subs"
main = "_worker.js"
compatibility_date = "2025-07-23"
keep_vars = true

# 添加一些额外的配置以增强兼容性
compatibility_flags = []
workers_dev = true

[[kv_namespaces]]
binding = "KV"			                    #KV绑定名默认不可修改
id = "91745742191d44ea8cf33403dfcf96d2"		#KV据库id

[vars]
SUBAPI = "SUBAPI.cmliussss.net"
SUBCONFIG = "https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online_MultiCountry.ini"
TOKEN = "wh898"

[[routes]]
pattern = "cf-subs.wh8.xx.kg"
custom_domain = true
zone_name = "wh8.xx.kg"